channels:
  - https://conda.anaconda.org/conda-forge
dependencies:
  - python=3.7
  - blosc
  - coverage
  - nose
  - pip
  - pytables
  - pytest
  - pytest-cov
  - python=3.7
  - pip:
    - msgpack>=1.0.0
    - sphinx-autodoc-annotation
